---

- hosts: remote-ubuntu
  become: true
  tasks: 
  
  - name: install ssh-tools Ubuntu
    apt: 
      name: 
        - ssh-tools
      state: latest
      update_cache: yes

- hosts: remote-rhel
  become: true
  tasks:

  - name: install ssh-tools RedHat
    yum:
      name:
        - ssh-tools
      state: latest
      update_cache: yes

