---

- hosts: remote-ubuntu
  become: true
  tasks: 
  
  - name: install mc Ubuntu
    apt: 
      name: 
        - mc
      state: latest
      update_cache: yes

- hosts: remote-rhel
  become: true
  tasks:

  - name: install mc RedHat
    yum:
      name:
        - mc
      state: latest
      update_cache: yes

