---

- hosts: all
  become: true
  tasks: 
  
  - name: install apache and php-mod for Ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php-mod for Ubuntu
    apt:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"

