---

- hosts: remote-rhel
  become: true
  tasks: 
   
  - name: install updates for RedHat
    tags: updates
    yum: 
      update_only: yes 
      update_cache: yes 
    when: ansible_distribution == "RedHat"

  - name: install apache and php-mod for RedHat
    tags: install
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: start httpd (apache) for RedHat
    tags: httpd-start
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

  - name: change listen port apache in Rhel
    tags: apache-port-change
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen'
      line: Listen 90
    when: ansible_distribution == "RedHat"

  - name: Service restart for Rhel
    tags: apache-restart
    service:
      name: httpd
      state: restarted
    when: ansible_distribution == "RedHat"


- hosts: remote-ubuntu
  become: true
  tasks:

  - name: install updates for Ubuntu
    tags: updates
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php-mod for Ubuntu
    tags: install
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: start apache for Ubuntu
    tags: apache-start
    service:
      name: apache2
      state: started
      enabled: yes 
    when: ansible_distribution == "Ubuntu"

  - name: change listen port apache in Ubuntu
    tags: apache-port-change
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen'
      line: Listen 90
    when: ansible_distribution == "Ubuntu"


  - name: Service restart for Ubuntu
    tags: apache-restart
    service:
      name: apache2
      state: restarted
    when: ansible_distribution == "Ubuntu"



- hosts: all 
  become: true
  tasks: 

  - name: Add the user 'messi' with a specific uid and a primary group of 'unix_users'
    tags: useradd
    user:
       name: messi
       uid: 1041
       group: unix_users

  - name: copy default html file for site 
    tags: apache,html-copy
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

